name: Bonjour
on:
  - push
  - pull_request 
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file:  './go.mod'
      - run: go version 
      - name: Makefile execution
        run: make all TAG=${{ github.ref_name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags')
        with:
          username: sivloc
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pushing Docker Image
        run: make release TAG=${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags')
