name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt install cowsay -y
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
      - name: Read Package.json
        id: package 
        uses: juliangruber/read-file-action@v1
        with:
          path: README.md
      - name: Echo README
        run: echo "${{ steps.package.outputs.content }}"
      - name: La vache fait meuh
        uses: Code-Hex/neo-cowsay-action@v1
        with: 
          message: "${{ steps.package.outputs.content }}"
